/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tempconverter;

import java.awt.Color;

/**
 *
 * @author Alex
 */
public class TempConverterGui extends javax.swing.JFrame {

    TempConverterService newConverterTempService = new TempConverterService();

    /**
     * Creates new form TempConverterGui
     */
    public TempConverterGui() {
        this.setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userInputPnl = new javax.swing.JPanel();
        tempInputLbl = new javax.swing.JLabel();
        tempInputTxt = new javax.swing.JTextField();
        convertTempBtn = new javax.swing.JButton();
        userFeedbackLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tempInputLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tempInputLbl.setText("Enter Temp Celsius: ");

        tempInputTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        convertTempBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        convertTempBtn.setText("Convert To Fahrenheight");
        convertTempBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertTempBtnActionPerformed(evt);
            }
        });

        userFeedbackLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout userInputPnlLayout = new javax.swing.GroupLayout(userInputPnl);
        userInputPnl.setLayout(userInputPnlLayout);
        userInputPnlLayout.setHorizontalGroup(
            userInputPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInputPnlLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(userInputPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInputPnlLayout.createSequentialGroup()
                        .addComponent(tempInputLbl)
                        .addGap(18, 18, 18)
                        .addComponent(tempInputTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userInputPnlLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(userInputPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(convertTempBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userFeedbackLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        userInputPnlLayout.setVerticalGroup(
            userInputPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInputPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInputPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tempInputLbl)
                    .addComponent(tempInputTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(convertTempBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(userFeedbackLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(userInputPnl, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void convertTempBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertTempBtnActionPerformed

        try {
            newConverterTempService.setFromTempType(new TempMeasurementCelsius());
            newConverterTempService.setToTempType(new TempMeasurementFahrenheight());
            newConverterTempService.convertTempAndReturnConvertedTemp(tempInputTxt.getText());
            userFeedbackLbl.setForeground(Color.BLACK);
            userFeedbackLbl.setText(newConverterTempService.getConvertedTemp() + newConverterTempService.getToTempDescription());
        } catch (RuntimeException re) {
            userFeedbackLbl.setForeground(Color.red);
            userFeedbackLbl.setText(re.getMessage());
        }
    }//GEN-LAST:event_convertTempBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertTempBtn;
    private javax.swing.JLabel tempInputLbl;
    private javax.swing.JTextField tempInputTxt;
    private javax.swing.JLabel userFeedbackLbl;
    private javax.swing.JPanel userInputPnl;
    // End of variables declaration//GEN-END:variables
}
